
name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 12.x
      uses: actions/setup-node@v3
      with:
        node-version: 12.x
        cache: 'npm'
    - run: npm ci
     
  build-prod:

    runs-on: ubuntu-latest
    environment: 'prod'

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 12.x
      uses: actions/setup-node@v3
      with:
        node-version: 12.x
        cache: 'npm'
    - run: npm ci
